name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: 27.1

      # Runs a single command using the runners shell
      - name: Byte-compile elisp files
        run: emacs --batch -f batch-byte-compile *.el

      - name: Run day1 solutions
        run: emacs --script day1.elc

      - name: Run day2 solutions
        run: emacs --script day2.elc

      - name: Run day3 solutions
        run: emacs --script day3.elc
